<div class="competition-container">
   <div class="competition-date">
      <div class="competition-date-q fll">
         <div class="competition-date-d">{dateStart}</div>
      </div>
      <div class="competition-line fll none">
         <div class="competition-line-l"></div>
      </div>
      <div class="competition-date-q fll">
         <div class="competition-date-d">{dateEnd}</div>
      </div>
      <div class="clear"></div>
   </div>
   <div class="competition-old-result" onclick="competition.oldResult()">
        Результат прошлого конкурса
   </div>
   <div class="competition-lenta">
      {competition-lenta}
   </div>
</div>