<div class="form-container">
    <div class="form-h-t">
       <h2>Не можете войти или забыли пароль?</h2>
    </div>
    <div class="form-block">
       <div class="form-input-pl">
          <div class="fll">
             <input type="email" id="r_email" class="r-input" placeholder="Введите email адрес">
          </div>
          <div class="fll">
             <button class="r-button" onclick="restore.submitForm()">далее</button>
          </div>
          <div class="clear"></div>
       </div>
    </div>
</div>