<!DOCTYPE html>
<html lang="ru">
   <head>
      <meta charset="utf-8" />
      <title id="title">Восстановление доступа | Nucleus</title>
      <link rel="shortcut icon" href="/tpl/img/favicon/favicon_main.png?1" />
      <meta name="theme-color" content="#04a7a3">
      <meta name="yandex-verification" content="7c6b5394085425a6" />
      <meta name="description" content="Nucleus - с нами каждый момент Вашей жизни станет куда счастливее. Не веришь, так попробуй! Присоединись!">
      <meta property="og:title" content="Восстановление доступа | Nucleus"/>
      <meta property="og:image" content="http://web-nucleus.com/tpl/img/image_url.jpg"/>
      <meta property="og:site_name" content="web-nucleus.com"/>
      <meta property="og:description" content="Nucleus - с нами каждый момент Вашей жизни станет куда счастливее. Не веришь, так попробуй! Присоединись!"/>
      <link rel="stylesheet" href="/tpl/css/main.css?16.9" media="screen" />
      <link rel="stylesheet" href="/tpl/css/restore.css?0.1" media="screen" />
      <script src="/tpl/js/advert.js"></script>
      <script src="/tpl/js/userInfo.js?1"></script>
      <script src="/tpl/js/main.js?5.7.1"></script>
   </head>
   <body>
      <header class="restore-header">
         <div class="s-header-content">
            <div class="header-d">
               <div class="header-logo fll">Восстановление доступа</div>
               <div class="header-q flr">Возникла проблема? <span>Посетите справочный центр</span>.</div>
               <div class="clear"></div>
            </div>
         </div>
      </header>
      
      <section class="main-section">{content}</section>
   </body>
</html>