<div class="form-container">
    <div class="form-h-t">
       <h2>Это Ваш аккаунт?</h2>
    </div>
    <div class="form-block">
       <div class="r-user-photo">
          <div class="r-photo" style="background-image: url({image})"></div>
          <div class="r-name">{name}</div>
          <div class="r-btn">
             <button class="main-button fll" onclick="restore.finish()">Да - это мой аккаунт</button>
             <button class="main-button fll btn-f" onclick="restore.noAccount()">Нет - это не я</button>
             <div class="clear"></div>
          </div>
       </div>
    </div>
</div>