<div class="status-email-ver">
   <div class="status-email-ver-header">
      Подтвердите email-адрес
   </div>
   <div class="status-email-ver-content">
     Для продолжения работы с сервисом необходимо подтвердить Email-адрес. За подтверждение Вы получите 10 баллов рейтинга.
     <div class="status-email-ver-btn">
        <button class="main-button" id="btn_send_email_v" onclick="emailVer.send();">Выслать письмо с подтверждением</button>
     </div>
   </div>
</div>