<div class="setting-block">
    <div class="settings-category settinsg-category-pad">Премиум настройки</div>
    <div class="settings-block">
       <div class="settings-block-descr fll">
           Тема оформления
       </div>
       <div class="settings-block-b fll">
           <select onchange="settings.gi(4, this.value)" class="setting-select">
                  <option value="standart">стандартная</option>
                  <option value="gold">премиум</option>
           </select>
       </div>
       <div class="clear"></div>
    </div>
</div>