<div class="vote-container">
    <div class="vote-header-container">
        Ваш голос <span>за</span>?
    </div>
    <div class="vote-content">
        <div class="vote vote-true" onclick="return vote.voteTrue({idp})"></div>
        <div class="vote-pt"></div>
        <div class="vote vote-false" onclick="return vote.voteFalse({idp})"></div>
    </div>
    <div class="vote-descr">
        После того, как Вы отдадите свой голос, у Вас появится возможность оставить комментарий, который
        также будет нести свои голоса в будущем. На рейтинг фотографии влияют такие факторы, как "голоса ЗА", количесво
        положительных комментариев.  
    </div>
</div>