<div class="comment-main-block-content-list">
   <div class="fll comment-main-block-content-list-author">
       <div class="user-rds-b" style="background-image: url({image})"></div>
   </div>
   <div class="fll comment-main-block-content-list-info">
      <div class="comment-main-block-content-list-name">
          <a href="/id{uid}" class="link" target="_blank">{name}</a>
      </div>
      <div class="comment-main-block-content-list-msg">{text}</div>
      <div class="comment-main-block-content-list-date">{date}</div>
   </div>
   <div class="clear"></div>
</div>
{comment-content}