<div class="box-access">
    <div class="box-access-title">
        Изменение email адреса
    </div>
    <div class="box-access-container">
        <div class="box-access-d">
            На новый Email адрес придет уведомление с подтверждением. Пожалуйста, подтвердите Ваш новый Email адрес. 
        </div>
        <div class="box-access-inp">
            <input type="email" class="" id="email">
        </div>
        <div class="box-access-footer">
            <button class="main-button btn-f" onclick="access.close()">отменить</button>
            <button class="main-button" onclick="access.emailUpdate()">изменить</button>
        </div>
    </div>
</div>