<div class="box-access">
    <div class="box-access-title">
        Подтвердите пароль
    </div>
    <div class="box-access-container">
        <div class="box-access-d">
            Для продолжения действия, пожалуйста, введите Ваш пароль:
        </div>
        <div class="box-access-inp">
            <input type="password" class="" id="password">
        </div>
        <div class="box-access-footer">
            <button class="main-button btn-f" onclick="access.close()">отменить</button>
            <button class="main-button" onclick="access.s()">продолжить</button>
        </div>
    </div>
</div>