<div class="box-access">
    <div class="box-access-title">
        Изменение имени
    </div>
    <div class="box-access-container">
        <div class="box-access-d">
            Мы просим Вас указывать свои настоящие имя и фамилия. Так гораздо удобнее будет друзьям найти Вас.  
        </div>
        <div class="box-access-inp">
            <input type="text" class="" id="new_f_name" placeholder="Ваше имя:">
            <input type="text" class="" id="new_l_name" placeholder="Ваша фамилия:">
        </div>
        <div class="box-access-footer">
            <button class="main-button btn-f" onclick="access.close()">отменить</button>
            <button class="main-button" onclick="access.nameUpdate()">изменить</button>
        </div>
    </div>
</div>