<div class="box-access">
    <div class="box-access-title">
        Изменение пароля
    </div>
    <div class="box-access-container">
        <div class="box-access-d">
            Введите новый пароль. Пароль должен быть неменьше 6 символов.
        </div>
        <div class="box-access-inp">
            <input type="password" class="" id="password">
        </div>
        <div class="box-access-footer">
            <button class="main-button btn-f" onclick="access.close()">отменить</button>
            <button class="main-button" onclick="access.passwordUpdate()">сохранить</button>
        </div>
    </div>
</div>