<div id="ajax_page">
   <div class="search-main">
      <div class="page-header" id="search_processing">
         Поиск
      </div>
      <div class="search-main-container">
         <div class="search-main-container-form">
            <input class="search-input" type="search" id="search_input" onkeyup="search.req(event, this.value)" onkeydown="search.e(event, this.value)">
         </div>
      </div>
      <div class="search-result" id="search_result_block">
         Здесь Вы увидите результат поиска.
      </div>
    </div>
</div>