<!DOCTYPE html>
<html lang="ru" appcache="cache/cache.appcache">
   <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <title id="title">О нас</title>
      <link rel="stylesheet" href="/tpl/css/main.css?1" media="screen" />
      <link rel="stylesheet" href="/tpl/css/about.css?1" media="screen" />
   </head>
   <body>
      <header class="about-header">
        <div class="about-header-background"></div>
        <div class="pos-abs about-header-desrc">
           <div class="about-header-logo">
             <span class="about-header-span-logo">n</span>
           </div>
           <div class="about-header-h">
             <span class="about-header-span-h">Добро пожаловать в <br/> новую вселенную!</span>
           </div>
        </div>
      </header>
      <section class="about-section-main">
        <div class="fll about-section-author-img"></div>
        <div class="fll about-section-author-descr">
            <div class="about-section-author-desrc-title">Коротко и ясно</div>
            <div class="about-section-author-desrc-text">
              <i>Всем привет!</i><br/>
              <i>Я очень рад видеть Вас на нашем сайте. Давайте мы все дружно 
              поможем сайту в его развитии. Просто расскажите о нас, приглашайте
              своих друзей и друзей Ваших друзей. Все мы сделаем сервис лучше!</i><br/><br/>
              <i>Расскажу о сервисе. <br/> Это не плагиат инстаграмма. Это что-то новое. Новое, потому что уникальное.
              Я еще не видел на просторах интернета сервиса, который бы платил за фотографии каждому пользователю.
              Заинтересовал? Тогда присоединяйся, делись и рассказывай о нас! </i><br/><br/>
              <i><b>Стань королем интернета. Выйграй главный приз и будь номером 1!</b></i>
              <div class="about-sign-author">
                  <i>Ваш автор и главный разработчик <br/> Артем Молодцов!</i>
              </div>
            </div>
            <div class="about-section-author-desrc-bg-color"></div>
        </div>
        <div class="clear"></div>
      </section>
      <section class="link-f-m">
            <div class="footer-link">
                <div class="fll" style="width: calc(100% / 3)">
                    <span><a href="/" class="footer-link-a">Nucleus 1.0</a></span>
                </div>
                <div class="fll" style="width: calc(100% / 3);text-align: center;">
                    <span><a href="/about" class="footer-link-a">о нас</a></span>
                    <span><a href="/terms" class="footer-link-a">правила</a></span>
                </div>
                <div class="flr" style="width: calc(100% / 3); text-align: right;">
                    <span>2016</span>
                </div>
                <div class="clear"></div>
            </div>
       </section>
   </body>
</html>