<div id="ajax_page">
  <div class="store--bonus">
    <section class="header-promocode">
      <h2>Активируйте промокод Nucleus</h2>
    </section>
    <section class="promocode-content">
      <div class="promocode_coupon">
        <div class="promocode_coupon_side promocode_coupon_side--font">
          <div class="promocode_coupon_side--logo">Nucleus</div>
          <input type="text" autofocus autocomplete="off" onkeydown="promocode.onKeyDownActivate(event);" class="promocode_coupon_side--input" id="promocode_input"/>
          <div id="promocode_error">Введите промокод. Внимание! Вводите только цифры или буквы!</div>
        </div>
        <div class="promocode_coupon_side promocode_coupon_side--back">
          <div class="promocode_coupon_side--logo">Вы активировали промокод!</div>
          <div class="promocode-opacity-logo">Nucleus</div>
        </div>
      </div>
      <button class="main-button" onclick="promocode.activateBonus(event);">Активировать промокод</button>
     </section>
     <section class="descr-promocode">
       <h2>Что даёт промокод Nucleus? Что? Как? И почему?</h2>
       <span>Промокод позволяет получить баллы к рейтингу, различные подарки и бонусы. Каждый код можно активировать только 1 раз, а также в некоторых случаях он может иметь ограничение на активацию, т.е. первые 1000 или n-е количество первых успевшых получить код пользователей.</span>
     </section>
     <section class="descr-promocode">
       <h2>Как получить промокод Nucleus?</h2>
       <span>Запросить промокод самостоятельно нельзя. Nucleus и его партнёры могут предложить его Вам в рамках акций, профильных мероприятий и событий.</span>
     </section>
     <div class="pad15"></div>
    </div>
  </div> 
</div>