<div id="ajax_page">
  <div class="a-block-con">
    <div class="a-block-con-header">
      Ошибки
    </div>
    <div class="a-block-con-main">
      <div class="fll a-block-label">Всего ошибок:</div>
      <div class="fll a-block-num-l">{cnt-all-errors}</div>
      <div class="fll a-block-label">Принятых ошибок:</div>
      <div class="fll a-block-num-l">{cnt-all-errors-true}</div>
      <div class="clear"></div>
    </div>
    <div class="pad10"></div>
  </div>
  {list-errors}
</div> 