<div id="ajax_page">
  <div class="a-block-con">
    <div class="a-block-con-header">
      Фотографии
    </div>
    <div class="a-block-con-main">
      <div class="a-input-w">
        <input type="text" id="photo_id" class="a-input" placeholder="ID фотографии">
      </div>
      <div class="a-btn-block">
        <button onclick="admin.delPhoto()" class="a-btn-main">Удалить фотографию</button>
        <button onclick="admin.zeroRatingPhoto()" class="a-btn-main">Обнулить рейтинг</button>
        <div id="status"></div>
      </div>
    </div>
    <div class="pad10"></div>
  </div>
</div> 