<div id="ajax_page">
  <div class="a-block-con">
    <div class="a-block-con-header">
      Жалобы пользователей
    </div>
    <div class="a-block-con-main">
      <div class="fll a-block-label">Всего жалоб:</div>
      <div class="fll a-block-num-l">{cnt-all-report}</div>
      <div class="fll a-block-label">Принятых жалоб:</div>
      <div class="fll a-block-num-l">{cnt-all-report-true}</div>
      <div class="clear"></div>
    </div>
    <div class="pad10"></div>
  </div>
  {list-report}
</div> 