<div id="ajax_page">
  <div class="a-block-con">
    <div class="a-block-con-header">
       Общая статистика
    </div>
    <div class="a-block-con-main">
      <div class="fll a-block-label">Всего пользователей:</div>
      <div class="fll a-block-num-l">{cnt-all-users}</div>
      <div class="fll a-block-label">Всего фотографий:</div>
      <div class="fll a-block-num-l">{cnt-all-photo}</div>
      <div class="clear"></div>
    </div>
    <div class="pad10"></div>
  </div>
</div> 