<div class="search-result-list">
   <a href="/id{uid}" target="_blank">
      <div class="search-result-user-photo fll" style="background-image: url({photo_src})"></div>
   </a>
   <div class="search-result-user-info fll">
      <div class="search-result-info-name">
         <a href="/id{uid}" target="_blank">{name}</a>
      </div>
      <div class="search-result-rating"></div>
   </div>
   <div class="clear"></div>
</div>
{list}