<div id="ajax_page">
  <div class="room-message-main">
    <div class="room-message-container" id="room_message_container">
      <div class="room-example-msg" id="room_btn_start_example">
        <button class="main-button" onclick="room.message.startTest()">Начать</button>
      </div>
    </div>
    <div class="room-message-footer">
      <div class="room-message-f-container">
        <textarea class="room-textarea" id="msg_textarea" placeholder="Текст Вашего сообщения"></textarea>
        <button class="room-mobile-btn" onclick="" id="btn_send_test_mobile"></button>
        <div class="room-footer-btn">
          <div class="room-btn-send fll room-text-sp">
            Все действия на данной странице не сохраняются.
          </div>
          <div class="room-btn-send flr">
            <button class="main-button btn-room-pc" onclick="" id="btn_send_test">Отправить</button>
          </div>
          <div class="clear"></div>
        </div>
      </div>
    </div>
  </div>
</div>