<div id="ajax_page">
  <div class="room-category-main">
    <div class="page-header">Комната общения | Категории</div>
    <div class="room-category-container">
      <div class="room-category-list">
        <div class="room-category-list-title">Начало</div>
        <div class="room-category-list-p fll" onclick="room.category.start()">Знакомство</div>
        <div class="clear"></div>
      </div>
      <div class="room-category-list">
        <div class="room-category-list-title" data-main-category=1>Спорт</div>
        <div class="room-category-list-p fll" data-category=1 data-subcategory=1>Футбол</div>
        <div class="room-category-list-p fll" data-category=1 data-subcategory=2>Хоккей</div>
        <div class="room-category-list-p fll" data-category=1 data-subcategory=3>Волейбол</div>
        <div class="room-category-list-p fll room-category-list-p-none" onclick="room.category.none();">нет категории</div>
        <div class="clear"></div>
      </div>
      <div class="room-category-list">
        <div class="room-category-list-title" data-main-category=2>Общение</div>
        <div class="room-category-list-p fll" data-category=2 data-subcategory=1>С девушкой</div>
        <div class="room-category-list-p fll" data-category=2 data-subcategory=2>С парнем</div>
        <div class="clear"></div>
      </div>
      <div class="room-category-list">
        <div class="room-category-list-title" data-main-category=3>Игры</div>
        <div class="room-category-list-p fll" data-category=3 data-subcategory=1>GTA</div>
        <div class="room-category-list-p fll" data-category=3 data-subcategory=2>World of tanks</div>
        <div class="room-category-list-p fll" data-category=3 data-subcategory=3>FIFA</div>
        <div class="room-category-list-p fll" data-category=3 data-subcategory=4>PES</div>
        <div class="room-category-list-p fll" data-category=3 data-subcategory=5>LEFT 4 DEAD 2</div>
        <div class="room-category-list-p fll" data-category=3 data-subcategory=6>League of Legends</div>
        <div class="room-category-list-p fll" data-category=3 data-subcategory=7>Call of Duty</div>
        <div class="room-category-list-p fll" data-category=3 data-subcategory=8>Need for speed</div>
        <div class="room-category-list-p fll room-category-list-p-none" onclick="room.category.none();">нет категории</div>
        <div class="clear"></div>
      </div>
      <div class="room-category-list">
        <div class="room-category-list-title">Мне повезет</div>
        <div class="room-category-list-p fll">Поехали!</div>
        <div class="clear"></div>
      </div>
    </div>
    <div class="pad10"></div>
  </div>
</div>