<div id="ajax_page">
  <div class="room-message-main">
    <div class="room-message-container" id="room_message_container"></div>
    <div class="room-message-footer">
      <div class="room-message-f-container">
        <textarea class="room-textarea" id="msg_textarea" placeholder="Текст Вашего сообщения"></textarea>
        <div class="room-footer-btn">
          <div class="room-btn-send flr">
            <button class="main-button" onclick="room.message.send()">Отправить</button>
          </div>
          <div class="clear"></div>
        </div>
      </div>
    </div>
  </div>
</div>