<div id="ajax_page">
    <div class="fll profile-left-panel">
        <div class="profile-photo-block">
            <img src="https://pp.vk.me/c622131/v622131262/4bea6/vuFyWKuuaS4.jpg" alt="Артем Молодцов" class="user-photo-orig"/>
        </div>
    </div>  
    <div class="flr profile-right-panel">
        <div class="profile-info">
           <div class="profile-name fll">
           	   <h2>Артем Молодцов</h2>
           </div>
           <div class="flr online-status">
               <small>Online</small>
           </div>
           <div class="clear"></div>
           <div class="br"></div>
           <div class="tab-pad">
           		<div class="fll tab-info-1 tab-info">
                    <div>День рождения: </div>
                    <div>Пол: </div>
                    <div>Город:</div>
                    <div>Email:</div>
                    <div>Телефон:</div>
                </div>
                <div class="tab-info-2 tab-info fll">
                    <div><a href="">17 ноября</a></div>
                    <div><a href="">мужской</a></div>
                    <div><a href="">Кириши</a></div>
                    <div><a href="">molodcov.artyom@mail.ru</a></div>
                    <div><a href="">+79522018824</a></div>
                </div>
            </div>
           <div class="clear"></div>
        </div>

        <div class="profile-info">
           <div class="profile-name">
           	   <h2>Обо мне</h2>
           </div>
           <div class="br"></div>
           <div style="padding-top: 10px; padding-bottom: 10px;">
           	   Я начал увлекаться Web - разработкой еще в 8 классе, когда мне было интересно знать, как работают большие сайты,
           	   такие как ВКонтакте, Facebook, Google. И мне захотелось создать что-то свое, похожее на эти сайты, но не знал как.<br/><br/>
           	   Для примера я скачивал социальные движки Yii и другие, смотрел, как они работают и с каждым разом понимал, что мне становится все интересней. После чего я захотел окунуться в эту сферу и познать ее. Так я изучил сначала <b>HTML</b>, <b>CSS</b>. Потом заинтересовался <b>PHP</b> и <b>JavaScript</b>. 
           	   <br/><br/>
           	   Больше 2-х лет пишу Web-приложения, но каждый раз узнаю что-то новое, т.е. прогресс идет, а это хорошо!
           </div>
           <div class="profile-name" style="padding-top: 10px">
           	   <h2>Что я знаю и умею?</h2>
           </div>
           <div class="br"></div>
           <div style="padding-top: 10px; padding-bottom: 10px;">
           	   <b>1.</b> Свободно применяю такие технологии, как: PHP, JavaScript, HTML5, CSS3.<br/>
           	   <b>2.</b> Знаю и умею: Memcached, Node.JS, MySQL, Git.<br/>
           	   <b>3.</b> Есть опыт работы с такими языками программирования как: Python, C++, Java.<br/>
               <b>4.</b> Имеются навыки сложной кроссбраузерной вёрстки.<br/>
           </div>
           <div class="profile-name" style="padding-top: 10px">
           	   <h2>Репозиторий на GitHub'e</h2>
           </div>
           <div class="br"></div>
           <div style="padding-top: 10px; padding-bottom: 10px;">
               <a href="https://github.com/artemmolod/">Здесь</a> можно найти исходный код данного проекта.
           </div>
        </div>
    </div>
</div>