<div class="profile-button-block">
    <div class="profile-button">
        <button class="profile-btn {none}" id="{btn_friends}" onclick="{onclick}">Добавить в подписки</button>
        <button class="profile-btn {none2}" id="{btn_friends2}" onclick="{onclick2}">Отписаться</button>
        <button class="profile-btn {none3}" id="{btn_friends3}" onclick="{onclick3}">Разблокировать</button>
    </div>
    <div class="profile-button">
        <button class="profile-btn btn-report" onclick="report.show({uid}, 'user')">Пожаловаться</button>
    </div>
</div>